### PR TITLE
Better Visualizer

### PR DESCRIPTION
**Pull request by Matter-Shifter**
Sorry for what I did before.
---------
Here is my better visualizer suggestion. It can be switched between the better one and the default.

### CODE REVIEW

**Comment by MarcoPixel** [comment]
Hello @Matter-Shifter!

Thanks for your contribution and also thanks for resubmitting it as one pull request. 

I just have looked over your code and tried it side by side with the current build i have and i have to say its a small improvement in the smoothness area but you lost a lot of detail in that progress. 

Let me show you what i mean with this screenshot:

Image

You see the left and the right side of the spectrum kinda going flat there, right? That's because you smoothed the values together with the values in MeasureBandsSmoothed and it just gets mushy. 

You got some great ideas (like implementing an equalizer to adjust the values) but in the current state it's not possible to merge it to the main branch. If you get it to keep the level of detail and make it smoother feel free to send another pull request and i will have a look :)

**Comment by Matter-Shifter** [comment]
Hey @MarcoPixel,

Now you mentioned about it. I'd prefer higher FFTSize (e.g: FFTSize:6144) and lower sensitivity (below 30), so it may look like this. Also, AverageSize is 1, due to some limitations of my PC.

image

For me, the left side of spectrum is fine, but you're right that you said the right side of spectrum gets mushy...

Thanks for the comment, I'm glad to hear that and I appreciate it. I'll do my best next time. (•♦•)/

**Comment by tjhrulz** [comment]
I do like though that you added a nice simple switch for it which would make it much easier if someone wants to keep it the old way. However I see a few other changes in there, if that switch is off is it 100% the same as the old way?

**Comment by Matter-Shifter** [comment]
Exactly. The switch is 100% same as the old way as it switched off, but the other value like AverageSize, Sensitivity, etc. doesn't change.

**Comment by tjhrulz** [comment]
Since I am back working on rainmeter stuff today I'll try to take a further look at this today and see if I can make some tweaks to it to make it better/closer to the videos.

**Comment by Matter-Shifter** [comment]
Oh, nice. Glad to hear that. I'm also looking forward to it. I'll make a pull request once I've done what I did.

**Pull request closed without merging**
