### PR TITLE
Better Visualizer

### PR DESCRIPTION
**Pull request by Matter-Shifter**
Improved Smoothing and New Smoothing Customization.
----------
Hi @MarcoPixel,

It's been a while. As you promised, I've twerk the spectrum. I also made a small change in visualizer and some changes in my MeasureBandsSmoothed1.inc. I'd made some coding mistakes before in my MeasureBandsSmoothed1.inc, but it doesn't affect the spectrum. 

Next, this idea was made for those who wanted to customize the smoothing. I've made a new file - MeasureBandsSmoothed2.inc. This file may be slightly same as the default one, but still using my multipliers and divider for customization.

What do you think? I hope you like the changes and my idea. That's all. Thanks.

### CODE REVIEW

**Comment by tjhrulz** [comment]
Unless I am missing something I don't seem to see any change with the version I just pulled from your repo. I'll try playing around with it to see what I am doing wrong.
Any chance you could make a gifv comparison between this one, the old one, and the one in the videos?

**Comment by Matter-Shifter** [comment]
Unfortunately, I can't make gifv. But, I got some screenshots.

The mistakes shown in this picture (supposedly 2 split pictures but I merged it):
unnamed

I could do this kinda comparison, but doing all at once, my laptop is done:
image

**Comment by cab13140** [comment]
Hey @Matter-Shifter !
I've cloned your branch, and it looks a bit better... Still some stuff to change !
I've made a comparaison, will upload and edit.
Also, I can't make the dynamic genre colors working... It worked well with the unmodified visualizer,  but now it is always showing the base color. I don't see where is the problem there.

**Comment by Matter-Shifter** [comment]
Hey, it's been a while.

I did some changes in my branch(more twerking), and I did a video to compare both better and stock smoothing. [Here](https://youtu.be/Eis73TAcl7I). I hope you satisfied with the result.

The changes that I did may consume more memory and use more cpu.

**Comment by cab13140** [comment]
> The changes that I did consume more memory and use more cpu
The changes are great but I think we've reached a point where even mid-budget CPUs will be struggling. My i7 is working but fps not stable. I've found that using a value between 6000-7500 is a good balance. I'm using 7100 for now.

**Comment by tjhrulz** [comment]
Not to sound rude but there is no reason to take a CPU hit after all the past and ongoing attempts to reduce it, especially since it is only marginally closer to the effect in the videos.

This is just not something we want compromise on to add to the project. Even if we did take the CPU and latency hit to try to replicate it will be almost impossible to replicate the visualizer from the videos since we have to do it in real time.

**Comment by cab13140** [comment]
Maybe. But you should document FFTSize in the settings and explain to the user the effects of it. Also I'll stay with the old version from Matter-Shifter which was better while not consuming as much CPU.

**Pull request closed without merging**
