### PR TITLE
Updated SpotifyPlugin to 2.1.0

### PR DESCRIPTION
**Pull request by RobertFrydenlund**
Realized that this project was still using SpotifyPlugin 1.3.0, and that version had some issues connecting the WebAPI. Updated to 2.1.0 so 9fafc3f695667bcaa4f258e187c6339449f467f8 should work for all users. SpotifyPlugin now only connects to the WebAPI when you issue the first command to it https://github.com/RobertFrydenlund/SpotifyPlugin/commit/b7029c26470e667822f4faaf64a4857a8e868529.

### CODE REVIEW

**Comment by MarcoPixel** [comment]
@RobertFrydenlund Nice work, seems to work perfectly so far.

 Only thing is that the position and length are still outputted as seconds, not as MM:SS. If you could add a option to toggle between those modes or change it back to the original state that would be great. :)

Waiting for your response :)

**Comment by RobertFrydenlund** [comment]
@MarcoPixel Thank you, I will get right on it :)

**Comment by MarcoPixel** [comment]
@RobertFrydenlund Nice, thanks for the quick reply 👍 Just commit the changes and tell me when you're ready :)

**Comment by RobertFrydenlund** [comment]
Everything is working great on my end now. Should probably try to get this through as fast as possible as the old API keys are disabled now.

**Comment by MarcoPixel** [comment]
@RobertFrydenlund Works here too as expected :)

Nice work as always, gonna prepare the next release with the latest changes 👍

**Comment by tjhrulz** [comment]
@RobertFrydenlund What do you think about making some of the commands fallback to local commands if the user is not premium (Which it should probably documented that that is needed for these commands)

Also I may send a PR in a few days if I get a chance to make a few of the commands accept other inputs (i.e. relative volume changes or cycling repeat states)

**Comment by RobertFrydenlund** [comment]
@tjhrulz All measures are local, and doing command locally is so painful that I didn't even try to implement them before the web api got released. Relative volume changes should be quite easy to implement as you can just poll the volume from the local api and add an offset. I can implement cycling repeat, that shouldnt be an issue :)

**Comment by tjhrulz** [comment]
It would also be nice if the repeat and shuffle could also take 0, 1 and 2 so they are more NowPlaying like.

But yeah the few local commands you can do are pretty painful to do (And why people are having issue right now because Spotify forgot their class name) but if they were in the plugin then we could just force everyone over to using your plugin and put that issue behind us (Which is why I was willing to undertake adding them myself as I had already begun doing all of what I mentioned above)

P.S. You forgot to say measure types are defined with Type= with the new README and SetPosition should probably be added to the list

**Comment by RobertFrydenlund** [comment]
Should be fixed in #152. Works fine here, but i would love if you could test it as well, as i do sometimes miss things :)

**Pull request merged**
